"""Fix many to many:
;


Revision ID: 1d88f04a4acc
Revises: f17dfe1329a9
Create Date: 2022-07-17 20:13:37.099393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d88f04a4acc'
down_revision = 'f17dfe1329a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('route_points_route_id_fkey', 'route_points', type_='foreignkey')
    op.drop_constraint('route_points_point_id_fkey', 'route_points', type_='foreignkey')
    op.create_foreign_key(None, 'route_points', 'routes', ['route_id'], ['id'])
    op.create_foreign_key(None, 'route_points', 'points', ['point_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route_points', type_='foreignkey')
    op.drop_constraint(None, 'route_points', type_='foreignkey')
    op.create_foreign_key('route_points_point_id_fkey', 'route_points', 'routes', ['point_id'], ['id'])
    op.create_foreign_key('route_points_route_id_fkey', 'route_points', 'points', ['route_id'], ['id'])
    # ### end Alembic commands ###
