"""Remove unique user

Revision ID: f17dfe1329a9
Revises: 48ea7a5417f5
Create Date: 2022-07-17 20:05:44.044066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17dfe1329a9'
down_revision = '48ea7a5417f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('routes_user_id_key', 'routes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('routes_user_id_key', 'routes', ['user_id'])
    # ### end Alembic commands ###
